export enum UserRole {
  STUDENT = "STUDENT",
  TEACHER = "TEACHER",
  ADMIN = "ADMIN",
}

export enum OnboardingStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}

export enum AssignmentStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum SubmissionStatus {
  SUBMITTED = "SUBMITTED",
  GRADED = "GRADED",
  RETURNED = "RETURNED",
}

export enum XPSource {
  ASSIGNMENT_SUBMIT = "ASSIGNMENT_SUBMIT",
  ASSIGNMENT_GRADE = "ASSIGNMENT_GRADE",
  DAILY_LOGIN = "DAILY_LOGIN",
  FIRST_TOOL_USE = "FIRST_TOOL_USE",
  EARLY_SUBMISSION = "EARLY_SUBMISSION",
  DAILY_CHALLENGE = "DAILY_CHALLENGE",
  STREAK_BONUS = "STREAK_BONUS",
  BADGE_EARNED = "BADGE_EARNED",
  TEACHER_BONUS = "TEACHER_BONUS",
}

export enum ToolCategory {
  CHAT_AI = "CHAT_AI",
  CODE_AI = "CODE_AI",
  IMAGE_AI = "IMAGE_AI",
  WRITING_AI = "WRITING_AI",
  RESEARCH_AI = "RESEARCH_AI",
}

export enum NotificationType {
  ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED",
  GRADE_RECEIVED = "GRADE_RECEIVED",
  BADGE_EARNED = "BADGE_EARNED",
  LEVEL_UP = "LEVEL_UP",
  TEACHER_MESSAGE = "TEACHER_MESSAGE",
  DEADLINE_REMINDER = "DEADLINE_REMINDER",
  STREAK_BONUS = "STREAK_BONUS",
}
